config/routes.rb
Control::Application.routes.draw do

  resources :roles

  resources :entrances


  resources :purchases do
    resources :purchase_descriptions
  end


  resources :suppliers


  get "ingresolo" => "sessions#ingresolo", :as => "ingresolo"
  get "help" => "pages#help", :as => "help"
  get "video1" => "ayuda#video1", :as => "video1"

  resources :receipt_headers do
    get :autocomplete_city_name, :on => :collection
    resources :receipt_descriptions
  end 
  
  get 'receipt_descriptions/calc', to: 'receipt_descriptions#calc' 

  

  resources :conditions


  resources :states


  resources :production_orders do
    resources :procedures do 
  end

    resources :preproduction_costs
  end

  get "statistics" => "statistics#index", :as => "statistics"
  
  resources :statistics do
    collection do
      get :prints
    end
    collection do
      get :assemblies
    end
    collection do
      get :outlines
    end
    collection do
      get :embroideries
    end
    collection do
      get :cuts
    end
    collection do
      get :labels
    end
  end


  resources :donations


  resources :inputs
  resources :categories
  resources :unities
  
  resources :garments do
     resources :consume_garments 
  end
  
  get 'consume_garments/cal_cost', to: 'consume_garments#cal_cost'

  
  resources :types

  resources :clients do
      get :autocomplete_city_name, :on => :collection
  end  

  resources :docs

  resources :cities

  resources :regions

  resources :countries

  get "activate" => 'activations#create'

  root :to => "pages#home"

  
  get  "inventory" => "pages#inventory", :as => "inventory"
  get  "admin" => "pages#admin", :as => "admin"

  get "about" => "pages#about", :as => "about"

  resources :users do
      member do
        get :activate
      end
      get :autocomplete_center_name, :on => :collection
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :sessions, :only => [:new, :create, :destroy]

  resource :password_resets, :controller => "password_resets" #, :only => [:new, :edit]
  
  resources :centers
  resources :regionals
  resources :occupations

  resources :productions do
    collection do
         get :bars
    end
  end
  
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :garment
  attr_accessible :amount, :date, :description, :garment_id, :justification, :receiver, :user_id
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  def index
    @donations = Donation.page(params[:page]).per_page(3)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donations }
    end
  end

  def show
      @donation = Donation.find(params[:id])
  end

  def new
      @donation = Donation.new
  end

  def edit
      @donation = Donation.find(params[:id])
  end

  def create
      @donation = Donation.new(params[:donation])
      render :action => :new unless @donation.save
  end

  def update
      @donation = Donation.find(params[:id])
      render :action => :edit unless @donation.update_attributes(params[:donation])
  end

  def destroy
      @donation = Donation.find(params[:id])
      @donation.destroy
  end
  
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_donation.html.erb
<tr id=<%= "donation_#{donation.id}" %>>
    <td><%= donation.user.name %></td>
    <td><%= donation.garment.name %></td>
    <td><%= donation.amount %></td>
    <td><%= donation.description %></td>
    <td><%= donation.date %></td>
    <td><%= donation.justification %></td>
    <td><%= donation.receiver %></td>
    <td>
        <%= link_to image_tag('ver.png', :width=>'30', :title=>'Mostrar' ), donation_path(donation), :remote => true %>
        <%= link_to image_tag('edit.png', :width=>'30', :title=>'Editar' ), edit_donation_path(donation), :remote => true %>
        <%= link_to image_tag('destroy.png', :width=>'30', :title=>'Eliminar' ), donation_path(donation),
                    :method => :delete, :remote => true,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", 
                               :default => 'Are you sure?')) } %>
    </td>
</tr>

app/views/donations/_form.html.erb
 <script type="text/javascript">$(function() {
 $(".datepicker").datepicker();
});</script>

<%= simple_form_for(@donation, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.error_notification %>
  <%= display_base_errors @donation %>

  <div class="control-group">
    <label class="control-label" for="inputName">Responsable</label>
      <div class="controls">
        <%= f.association :user, :collection => User.all(:order => 'name'),:label => false, :required => true,
                             :input_html => {:class => 'span4' } %>
      </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputName">Prenda</label>
      <div class="controls">
        <%= f.association :garment, :collection => Garment.all(:order => 'name'),:label => false, :required => true,
                             :input_html => {:class => 'span4' } %>
      </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputName">Cantidad</label>
    <div class="controls">
        <%= f.input :amount, :label => false, :required => true,
                    :input_html => {:class => 'span4' } %>
     </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputName">Descripcion</label>
    <div class="controls">
        <%= f.input :description, :label => false, :required => true,
                    :input_html => {:class => 'span4' } %>
     </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputName">Fecha</label>
    <div class="controls">
        <%= f.input :date, :label => false, :required => true,
                    :input_html => { :class => 'span4 datepicker' } %>
     </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputName">Justificacion</label>
    <div class="controls">
        <%= f.input :justification, :label => false, :required => true,
                    :input_html => { :rows => '10', :class => 'span4' } %>
     </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="inputName">Recibe</label>
    <div class="controls">
        <%= f.input :receiver, :collection => User.all(:order => 'name'),:label => false, :required => true,
                             :input_html => {:class => 'span4' } %>
     </div>
  </div>

  
  <div id='fo' class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-primary' %>
    <a href="#" class="btn btn-inverse" onclick="$.lazybox.close()">Cerrar</a>
  </div>
<% end %>

app/views/donations/_show.html.erb
<div class='donation'>
    <%- model_class = Donation -%>

    <div class="responsive">

        <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="$.lazybox.close()">&times;</button>
             <h4>Donacion</h4>
        </div>

        <div class="modal-body">
            <dl class="dl-horizontal">
              <table class="table table-striped table-bordered table-condensed">
              	<tr>
              	 <th><strong>Responsable:</strong></th>
				 <td><%= @donation.user.name %></td>
				</tr>
				<tr>
				  <th><strong>Prenda:</strong></th>
				  <td><%= @donation.garment.name %></td>
				</tr>
				<tr>
				  <th><strong>Cantidad:</strong></th>
				  <td><%= @donation.amount %> Unidades</td>
				</tr>
				<tr>
				  <th><strong>Descripcion:</strong></th>
				  <td><%= @donation.description %></td>
				</tr>
				<tr>
				  <th><strong>Fecha:</strong></th>
				  <td><%= @donation.date %></td>
				</tr>
				<tr>
				  <th><strong>Justificacion:</strong></th>
				  <td><%= @donation.justification %></td>
				</tr>
				<tr>
				  <th><strong>Recibió:</strong></th>
				  <td><%= @donation.receiver %></td>
				</tr>
			  </table>
			</dl>
        </div>

        <div id='fo' class="modal-footer">
             <a href="#" class="btn" onclick="$.lazybox.close()">Cerrar</a>
        </div>

    </div>
</div>

app/views/donations/create.js.erb
$('table tbody').append("<%= escape_javascript(render @donation) %>")
$.lazybox.close()

app/views/donations/destroy.js.erb
$("table tr#donation_<%= @donation.id %>").remove();

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true, close: false, klass: 'sticker', fixed: true});

app/views/donations/index.html.erb
<%- model_class = Donation -%>
<div class="page-header">
  <h3 id='texto'>Donaciones</h3>
</div>
  <div id="buscar">
      <%= form_tag request.path, :class => "well", :method => 'get' do %>

        <div class = "row">
             <div class="span9">
                  <div class = "row">
                       <div class="span4">
                            <b>Donacion: </b> 
                            <%= text_field_tag :name, params[:name], 
                             :class=>"span3" %>
                       </div>
                       <div class="span1">
                           <%= submit_tag "Buscar", :name => nil, :class => 'btn btn-success' %>
                       </div>
                  </div>
             </div>
        </div>

      <% end %>
  </div>
<table class="table table-hover table-striped  table-bordered">
  <thead>
    <tr>
      <th>Responsable</th>
      <th>Prenda</th>
      <th>Cantidad</th>
      <th>Descripcion</th>
      <th>Fecha</th>
      <th>Justificacion</th>
      <th>Recibe:</th>	
      <th></th>
    </tr>
  </thead>
  <tbody>
     <%= render @donations %>
  </tbody>
  <tfoot>
  </tfoot>
</table>
<%= link_to 'Nueva Donacion', new_donation_path, :remote => true, :class => 'btn btn-primary' %>

<div id='ocupa' class="pagination">
   <ul>
      <%= will_paginate(@donations, :renderer => WillPaginate::ActionView::LinkRenderer,
                                :previous_label => '&laquo; Anterior', 
                                :next_label => 'Siguiente &raquo;') %>
   </ul>
   <p id='ocupa' class="pull-right">Total Donaciones : <%= @donations.count %></p>
</div>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path %>

app/views/donations/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>", {close: false, klass: 'sticker', fixed: true});

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @donation.user_id %>
</p>

<p>
  <b>Garment:</b>
  <%= @donation.garment_id %>
</p>

<p>
  <b>Amount:</b>
  <%= @donation.amount %>
</p>

<p>
  <b>Description:</b>
  <%= @donation.description %>
</p>

<p>
  <b>Date:</b>
  <%= @donation.date %>
</p>

<p>
  <b>Justification:</b>
  <%= @donation.justification %>
</p>

<p>
  <b>Receiver:</b>
  <%= @donation.receiver %>
</p>


<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/donations/show.js.erb
$.lazybox("<%= j(render 'show') %>", {close: false, klass: 'sticker', fixed: true})

app/views/donations/update.js.erb
$('tr#donation_<%= @donation.id %>').replaceWith("<%= escape_javascript(render @donation) %>")
$.lazybox.close()