config/routes.rb
Control::Application.routes.draw do

  resources :roles

  resources :entrances


  resources :purchases do
    resources :purchase_descriptions
  end


  resources :suppliers


  get "ingresolo" => "sessions#ingresolo", :as => "ingresolo"
  get "help" => "pages#help", :as => "help"
  get "video1" => "ayuda#video1", :as => "video1"

  resources :receipt_headers do
    get :autocomplete_city_name, :on => :collection
    resources :receipt_descriptions
  end 
  
  get 'receipt_descriptions/calc', to: 'receipt_descriptions#calc' 

  

  resources :conditions


  resources :states


  resources :production_orders do
    resources :procedures do 
  end

    resources :preproduction_costs
  end

  get "statistics" => "statistics#index", :as => "statistics"
  
  resources :statistics do
    collection do
      get :prints
    end
    collection do
      get :assemblies
    end
    collection do
      get :outlines
    end
    collection do
      get :embroideries
    end
    collection do
      get :cuts
    end
    collection do
      get :labels
    end
  end


  resources :donations


  resources :inputs
  resources :categories
  resources :unities
  
  resources :garments do
     resources :consume_garments 
  end
  
  get 'consume_garments/cal_cost', to: 'consume_garments#cal_cost'

  
  resources :types

  resources :clients do
      get :autocomplete_city_name, :on => :collection
  end  

  resources :docs

  resources :cities

  resources :regions

  resources :countries

  get "activate" => 'activations#create'

  root :to => "pages#home"

  
  get  "inventory" => "pages#inventory", :as => "inventory"
  get  "admin" => "pages#admin", :as => "admin"

  get "about" => "pages#about", :as => "about"

  resources :users do
      member do
        get :activate
      end
      get :autocomplete_center_name, :on => :collection
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :sessions, :only => [:new, :create, :destroy]

  resource :password_resets, :controller => "password_resets" #, :only => [:new, :edit]
  
  resources :centers
  resources :regionals
  resources :occupations

  resources :productions do
    collection do
         get :bars
    end
  end
  
end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
	belongs_to :production_order
	belongs_to :condition
	attr_accessible :embroidery_month, :print_month, :print_month, :cutting_month, :outline_month, :assembly_month, :washing_month, :tinte_month, :labeled_month, :stock_month, :store_month, :embroidery_amount, :print_amount, :print_amount, :cutting_amount, :outline_amount, :assembly_amount, :washing_amount, :tinte_amount, :labeled_amount, :stock_amount, :store_amount, :condition_id, :cutting_attendant, :embroidery_attendant, :print_attendant,  :outline_attendant, :assembly_attendant, :labeled_attendant, :washing_attendant, :tinte_attendant, :store_attendant, :stock_attendant, :stock_delivery, :stock_end, :stock_real, :store_delivery, :store_end, :store_real, :labeled_delivery, :labeled_end, :labeled_real,   :production_order_id, :assembly_delivery, :assembly_end, :assembly_real, :cutting_delivery, :cutting_end, :cutting_real, :embroidery_delivery, :embroidery_end, :embroidery_real, :outline_delivery, :outline_end, :outline_real, :print_delivery, :print_end, :print_real, :tinte_delivery, :tinte_end, :tinte_real, :washing_delivery, :washing_end, :washing_real
  
  def self.cut(fecha)
    str = fecha.split("-");
    @string = str[1]
  end

end 

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController

  before_filter :find_ids

  def index
      @procedures = @production_order.procedures.all 
  end

  def show

  end

  def new
      @procedure = Procedure.new
  end

  def edit
     
  end

  def create
      @procedure = Procedure.new(params[:procedure])
      @procedure.production_order_id = @production_order.id
      @procedure.print_month = Production.cut(@procedure.print_end)
      @procedure.embroidery_month = Production.cut(@procedure.embroidery_end)
      @procedure.assembly_month = Production.cut(@procedure.assembly_end)
      @procedure.outline_month = Production.cut(@procedure.outline_end)
      @procedure.cutting_month = Production.cut(@procedure.cutting_end)
      @procedure.labeled_month = Production.cut(@procedure.labeled_end)
      render :action => :new unless @procedure.save
  end

  def update
      @procedure.print_month = Production.cut(@procedure.print_end)
      @procedure.embroidery_month = Production.cut(@procedure.embroidery_end)
      @procedure.assembly_month = Production.cut(@procedure.assembly_end)
      @procedure.outline_month = Production.cut(@procedure.outline_end)
      @procedure.cutting_month = Production.cut(@procedure.cutting_end)
      @procedure.labeled_month = Production.cut(@procedure.labeled_end)
      render :action => :edit unless @procedure.update_attributes(params[:procedure])
      @procedure.save
  end

  def destroy
      @procedure.destroy
  end
  
  def find_ids 
      @production_order = ProductionOrder.find(params[:production_order_id])
      @procedure = Procedure.find(params[:id]) if params[:id]
  end  

end

app/helpers/procedures_helper.rb
module ProceduresHelper

  def leyenda
  	leyenda = []         # leyendas del grafico
    @data.collect do |key, value| 
    	case key
		when 1
		  leyenda << "Enero #{value} Unidades"
		when 2
		  leyenda << "Febrero #{value} Unidades"
		when 3
		  leyenda << "Marzo #{value} Unidades"
		when 4
		  leyenda << "Abril  #{value} Unidades"
		when 5
		  leyenda << "Mayo #{value} Unidades"
		when 6
		  leyenda << "Junio #{value} Unidades"
		when 7
		  leyenda << "Julio #{value} Unidades"
		when 8
		  leyenda << "Agosto #{value} Unidades"
	    when 9
		  leyenda << "Septiembre #{value} Unidades"
		when 10
		  leyenda << "Octubre #{value} Unidades"
		when 11
		  leyenda << "Noviembre #{value} Unidades"
		when 12
		  leyenda << "Diciembre #{value} Unidades"
		when nil
		  leyenda << "No Hay Valoracion"
		end
    end
    leyenda
  end

end

app/views/procedures/_form.html.erb
<%= javascript_include_tag "procedures.js" %>

<%= simple_form_for([@production_order, @procedure], :html => { :remote => true }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <table class="table table-striped table-bordered table-condensed">
            <tr>
                <td>
                  <th>Fecha Entrega</th>
                  <th>Fecha Real</th>
                  <th>Fecha Final</th>
                  <th>Encargado</th>
                  <th>Unidades</th>
                </td> 
            </tr>
            <tr>
              <th><strong>Bordado:</strong></th>
              <td><%= f.input :embroidery_delivery, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :embroidery_real, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :embroidery_end, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :embroidery_attendant, :label => false %></td>
              <td><%= f.input :embroidery_amount, :label => false %></td>
            </tr>
            <tr>
              <th><strong>Estampado:</strong></th>
              <td><%= f.input :print_delivery, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :print_real, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :print_end, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :print_attendant, :label => false %></td>
              <td><%= f.input :print_amount, :label => false %></td>
            </tr>
            <tr>
              <th><strong>Corte:</strong></th>
              <td><%= f.input :cutting_delivery, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :cutting_real, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :cutting_end, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :cutting_attendant, :label => false %></td>
              <td><%= f.input :cutting_amount, :label => false %></td>
            </tr>
            <tr>
              <th><strong>Trazo:</strong></th>
              <td><%= f.input :outline_delivery, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :outline_real, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :outline_end, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :outline_attendant, :label => false %></td>
              <td><%= f.input :outline_amount, :label => false %></td>
            </tr>
            <tr>
              <th><strong>Ensamblado:</strong></th>
              <td><%= f.input :assembly_delivery, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :assembly_real, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :assembly_end, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :assembly_attendant, :label => false %></td>
              <td><%= f.input :assembly_amount, :label => false %></td>
            </tr>
            <tr>
              <th><strong>Lavado:</strong></th>
              <td><%= f.input :washing_delivery, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :washing_real, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :washing_end, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :washing_attendant, :label => false %></td>
              <td><%= f.input :washing_amount, :label => false %></td>
            </tr>
            <tr>
              <th><strong>Tintoreria:</strong></th>
              <td><%= f.input :tinte_delivery, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :tinte_real, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :tinte_end, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :tinte_attendant, :label => false %></td>
              <td><%= f.input :tinte_amount, :label => false %></td>
            </tr>
            <tr>
              <th><strong>Etiquetado:</strong></th>
              <td><%= f.input :labeled_delivery, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :labeled_real, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :labeled_end, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :labeled_attendant, :label => false %></td>
              <td><%= f.input :labeled_amount, :label => false %></td>
            </tr>

            <tr>
              <th><strong>Bodega:</strong></th>
              <td><%= f.input :stock_delivery, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :stock_real, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :stock_end, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :stock_attendant, :label => false %></td>
              <td><%= f.input :stock_amount, :label => false %></td>
            </tr>
            <tr>
              <th><strong>Almacen:</strong></th>
              <td><%= f.input :store_delivery, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :store_real, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :store_end, :label => false, :input_html => {:class => 'datepicker' } %></td>
              <td><%= f.input :store_attendant, :label => false %></td>
              <td><%= f.input :store_amount, :label => false %></td>
            </tr>
            <tr>
              <th><strong>Estado:</strong></th>
              <td><%= f.association :condition, :collection => Condition.all(:order => 'name'), :label => false %></td>
            </tr>
          </table>
  </div>

  <div id='fo' class="form-actions">
    <%= f.button :submit, 'Guardar', :class=> 'btn btn-primary' %>
    <%= link_to 'Cerrar', production_order_procedures_path(@production_order), :remote => true, :class=>'btn btn-inverse' %>
  </div>
<% end %>

app/views/procedures/_index.html.erb
<%- model_class = Procedure -%>
<div class='procedures'>
 <div class="page-header">
   <h1>Procesos</h1>
   <img id='lazyimm' src="assets/logo_sena.png">
 </div>

 <table class="table table-striped table-bordered table-condensed table-hover">
   <thead>
     <tr> 
         
     </tr>
       </thead>
         <tbody>
            <%= render @procedures %>
         </tbody>
       <tfoot>
   </tfoot>
 </table>
 <div id='fo' class="form-actions">
 <%= link_to 'Nuevo Proceso', new_production_order_procedure_path(@production_order), :remote => true, :class => 'btn btn-primary' %>
  <a href="#" class="btn btn-inverse" onclick="$.lazybox.close()">Cerrar</a>
</div>

app/views/procedures/_procedure.html.erb
<tr id=<%= "procedure_#{procedure.id}" %>>

   <td>Proceso - <%= @procedures.index(procedure)+1 %>
       <%= image_tag procedure.condition.image.url(:small) %>
   </td>	
      
   <td>
       <%= link_to image_tag('ver.png', :width=>'30', :title=>'Mostrar' ), production_order_procedure_path(@production_order, procedure), :remote => true %>
       <%= link_to image_tag('edit.png', :width=>'30', :title=>'Editar' ),edit_production_order_procedure_path(@production_order, procedure), :remote => true %>
       <%= link_to image_tag('destroy.png', :width=>'30', :title=>'Eliminar' ), production_order_procedure_path(@production_order, procedure), :confirm => 'Are you sure you want to delete this entry? This is an irreversible action.', :method => :delete, :remote => true %>
   </td>
</tr>

app/views/procedures/_show.html.erb
<%- model_class = Procedure -%>
<div class="responsive">

    <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-hidden="true" 
         onclick="$.lazybox.close()">&times;</button>
         <h3>Procesos de la Prenda: <br>
          <%= @production_order.garment.name %>
         </h3>
         <h4>OP # <%= @production_order.op %></h4>
         <img id='lazyimme' src="assets/logo_sena.png">
    </div>

    <div class="modal-body">
      <div class="accordion" id="accordion1"> 
        <div class="accordion-group">
          <div class="accordion-heading">
            <a id='link' class="accordion-toggle" data-toggle="collapse"
                data-parent="#accordion1" href="#note1">
                Ver / Ocultar Fecha Trazado:
            </a>
          </div>
          <div class="accordion-body collapse in" id="note1">
            <div class="accordion-inner">
              <table class="table table-striped table-bordered table-condensed table-hover">
                <tr>
                    <td>
                      <th>Fecha Entrega</th>
                      <th>Fecha Real</th>
                      <th>Fecha Final</th>
                      <th>Encargado</th>
                      <th>Unidades</th>
                    </td> 
                </tr>
                <tr>
                  <th><strong>Trazado:</strong></th>
                  <td><%= @procedure.outline_delivery %></td>
                  <td><%= @procedure.outline_real %></td>
                  <td><%= @procedure.outline_end %></td>
                  <td><%= @procedure.outline_attendant %></td>
                  <td><%= @procedure.outline_amount %></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="accordion-group">
          <div class="accordion-heading">
            <a id='link' class="accordion-toggle" data-toggle="collapse"
              data-parent="#accordion1" href="#note2">
              Ver / Ocultar Fecha Corte/extendido:
            </a>
          </div>
          <div class="accordion-body collapse" id="note2">
            <div class="accordion-inner">
              <table class="table table-striped table-bordered table-condensed table-hover">
                <tr>
                    <td>
                      <th>Fecha Entrega</th>
                      <th>Fecha Real</th>
                      <th>Fecha Final</th>
                      <th>Encargado</th>
                      <th>unidades</th>
                    </td> 
                </tr>
                <tr>
                  <th><strong>Corte:</strong></th>
                  <td><%= @procedure.cutting_delivery %></td>
                  <td><%= @procedure.cutting_real %></td>
                  <td><%= @procedure.cutting_end %></td>
                  <td><%= @procedure.cutting_attendant%></td>
                  <td><%= @procedure.cutting_amount%></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="accordion-group">
          <div class="accordion-heading">
            <a id='link' class="accordion-toggle" data-toggle="collapse"
              data-parent="#accordion1" href="#note3">
              Ver / Ocultar Fecha Confeccion:
            </a>
          </div>
          <div class="accordion-body collapse" id="note3">
            <div class="accordion-inner">
              <table class="table table-striped table-bordered table-condensed table-hover">
                <tr>
                    <td>
                      <th>Fecha Entrega</th>
                      <th>Fecha Real</th>
                      <th>Fecha Final</th>
                      <th>Encargado</th>
                      <th>Unidades</th>
                    </td> 
                </tr>
                <tr>
                  <th><strong>Confe:</strong></th>
                    <td><%= @procedure.assembly_delivery %></td>
                    <td><%= @procedure.assembly_real %></td>
                    <td><%= @procedure.assembly_end %></td>
                    <td><%= @procedure.assembly_attendant %></td>
                    <td><%= @procedure.assembly_amount %></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="accordion-group">
          <div class="accordion-heading">
              <a id='link' class="accordion-toggle" data-toggle="collapse"
                data-parent="#accordion1" href="#note4">
                Ver / Ocultar Fecha Etiquetado:
              </a>
            </div>
          <div class="accordion-body collapse" id="note4">
            <div class="accordion-inner">
              <table class="table table-striped table-bordered table-condensed table-hover">
                <tr>
                    <td>
                      <th>Fecha Entrega</th>
                      <th>Fecha Real</th>
                      <th>Fecha Final</th>
                       <th>Encargado</th>
                       <th>Unidades</th>
                    </td> 
                </tr>
                <tr>
                  <th><strong>Etiquetado:</strong></th>
                  <td><%= @procedure.labeled_delivery %></td>
                  <td><%= @procedure.labeled_real %></td>
                  <td><%= @procedure.labeled_end %></td>
                  <td><%= @procedure.labeled_attendant %></td>
                  <td><%= @procedure.labeled_amount %></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="accordion-group">
          <div class="accordion-heading">
              <a id='link' class="accordion-toggle" data-toggle="collapse"
                data-parent="#accordion1" href="#note5">
                Ver / Ocultar Fecha Bordado:
              </a>
            </div>
          <div class="accordion-body collapse" id="note5">
            <div class="accordion-inner">
              <table class="table table-striped table-bordered table-condensed table-hover">
                <tr>
                    <td>
                      <th>Fecha Entrega</th>
                      <th>Fecha Real</th>
                      <th>Fecha Final</th>
                       <th>Encargado</th>
                       <th>Unidades</th>
                    </td> 
                </tr>
                <tr>
                  <th><strong>Bordado:</strong></th>
                  <td><%= @procedure.embroidery_delivery %></td>
                  <td><%= @procedure.embroidery_real %></td>
                  <td><%= @procedure.embroidery_end %></td>
                  <td><%= @procedure.embroidery_attendant %></td>
                  <td><%= @procedure.embroidery_amount %></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="accordion-group">
          <div class="accordion-heading">
              <a id='link' class="accordion-toggle" data-toggle="collapse"
                data-parent="#accordion1" href="#note6">
                Ver / Ocultar Fecha Estampado:
              </a>
            </div>
            <div class="accordion-body collapse" id="note6">
              <div class="accordion-inner">
                <table class="table table-striped table-bordered table-condensed table-hover">
                  <tr>
                      <td>
                        <th>Fecha Entrega</th>
                        <th>Fecha Real</th>
                        <th>Fecha Final</th>
                        <th>Encargado</th>
                        <th>Unidades</th>
                      </td> 
                  </tr>
                  <tr>
                  <th><strong>Estampado:</strong></th>
                  <td><%= @procedure.print_delivery %></td>
                  <td><%= @procedure.print_real %></td>
                  <td><%= @procedure.print_end %></td>
                  <td><%= @procedure.print_attendant %></td>
                  <td><%= @procedure.print_amount %></td>
                  </tr>
                </table>
              </div>
            </div>
        </div>
        <div class="accordion-group">
          <div class="accordion-heading">
              <a id='link' class="accordion-toggle" data-toggle="collapse"
                data-parent="#accordion1" href="#note7">
                Ver / Ocultar Fecha Tintoreria :
              </a>
            </div>
          <div class="accordion-body collapse" id="note7">
            <div class="accordion-inner">
              <table class="table table-striped table-bordered table-condensed table-hover">
                <tr>
                    <td>
                      <th>Fecha Entrega</th>
                      <th>Fecha Real</th>
                      <th>Fecha Final</th>
                      <th>Encargado</th>
                      <th>Unidades</th>
                    </td> 
                </tr>
                <tr>
                  <th><strong>Tintoreria:</strong></th>
                   <td><%= @procedure.tinte_delivery %></td>
                    <td><%= @procedure.tinte_real %></td>
                    <td><%= @procedure.tinte_end %></td>
                    <td><%= @procedure.tinte_attendant %></td>
                     <td><%= @procedure.tinte_amount %></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="accordion-group">
          <div class="accordion-heading">
              <a id='link' class="accordion-toggle" data-toggle="collapse"
                data-parent="#accordion1" href="#note8">
                Ver / Ocultar Fecha Lavado:
              </a>
          </div>
          <div class="accordion-body collapse" id="note8">
            <div class="accordion-inner">
              <table class="table table-striped table-bordered table-condensed table-hover">
                  <tr>
                      <td>
                        <th>Fecha Entrega</th>
                        <th>Fecha Real</th>
                        <th>Fecha Final</th>
                        <th>Encargado</th>
                        <th>Unidades</th>
                      </td> 
                  </tr>
                  <tr>
                    <th><strong>Lavado:</strong></th>
                    <td><%= @procedure.washing_delivery %></td>
                  <td><%= @procedure.washing_real %></td>
                  <td><%= @procedure.washing_end %></td>
                  <td><%= @procedure.washing_attendant %></td>
                  <td><%= @procedure.washing_amount %></td>
                  </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="accordion-group">
          <div class="accordion-heading">
              <a id='link' class="accordion-toggle" data-toggle="collapse"
                data-parent="#accordion1" href="#note9">
                Ver / Ocultar Fecha Entrega a Bodega:
              </a>
          </div>
          <div class="accordion-body collapse" id="note9">
            <div class="accordion-inner">
              <table class="table table-striped table-bordered table-condensed table-hover">
                  <tr>
                      <td>
                        <th>Fecha Entrega</th>
                        <th>Fecha Real</th>
                        <th>Fecha Final</th>
                        <th>Encargado</th>
                        <th>Unidades</th>
                      </td> 
                  </tr>
                  <tr>
                    <th><strong>Bodega:</strong></th>
                    <td><%= @procedure.stock_delivery %></td>
                    <td><%= @procedure.stock_real %></td>
                    <td><%= @procedure.stock_end %></td>
                    <td><%= @procedure.stock_attendant %></td>
                    <td><%= @procedure.stock_amount %></td>
                  </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="accordion-group">
          <div class="accordion-heading">
              <a id='link' class="accordion-toggle" data-toggle="collapse"
                data-parent="#accordion1" href="#note10">
                Ver / Ocultar Fecha Entrega a Almacen:
              </a>
          </div>
          <div class="accordion-body collapse" id="note10">
            <div class="accordion-inner">
              <table class="table table-striped table-bordered table-condensed table-hover">
                  <tr>
                      <td>
                        <th>Fecha Entrega</th>
                        <th>Fecha Real</th>
                        <th>Fecha Final</th>
                        <th>Encargado</th>
                        <th>Unidades</th>
                      </td> 
                  </tr>
                  <tr>
                    <th><strong>Almacen:</strong></th>
                    <td><%= @procedure.store_delivery %></td>
                    <td><%= @procedure.store_real %></td>
                    <td><%= @procedure.store_end %></td>
                    <td><%= @procedure.store_attendant %></td>
                    <td><%= @procedure.store_amount %></td>
                  </tr>
              </table>
            </div>
          </div>
        </div>
          <div id='fo' class="modal-footer">
                <%= link_to 'Cerrar', production_order_procedures_path(@production_order), :remote => true, :class=>'btn btn-inverse' %>
          </div>
    </div>
 </div>

app/views/procedures/create.js.erb
$.lazybox.close()

app/views/procedures/destroy.js.erb
$("table tr#procedure<%= @procedure.id %>").remove();

app/views/procedures/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true, close: false, klass: 'sticker', fixed: true});

app/views/procedures/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>", {close: false, klass: 'sticker', fixed: true});

app/views/procedures/show.js.erb
$.lazybox("<%= j(render 'show') %>", {close: false, klass: 'sticker', fixed: true})

app/views/procedures/update.js.erb
$('tr#procedure_<%= @procedure.id %>').replaceWith("<%= escape_javascript(render @procedure) %>")
$.lazybox.close()