config/routes.rb
Control::Application.routes.draw do

  resources :roles

  resources :entrances


  resources :purchases do
    resources :purchase_descriptions
  end


  resources :suppliers


  get "ingresolo" => "sessions#ingresolo", :as => "ingresolo"
  get "help" => "pages#help", :as => "help"
  get "video1" => "ayuda#video1", :as => "video1"

  resources :receipt_headers do
    get :autocomplete_city_name, :on => :collection
    resources :receipt_descriptions
  end 
  
  get 'receipt_descriptions/calc', to: 'receipt_descriptions#calc' 

  

  resources :conditions


  resources :states


  resources :production_orders do
    resources :procedures do 
  end

    resources :preproduction_costs
  end

  get "statistics" => "statistics#index", :as => "statistics"
  
  resources :statistics do
    collection do
      get :prints
    end
    collection do
      get :assemblies
    end
    collection do
      get :outlines
    end
    collection do
      get :embroideries
    end
    collection do
      get :cuts
    end
    collection do
      get :labels
    end
  end


  resources :donations


  resources :inputs
  resources :categories
  resources :unities
  
  resources :garments do
     resources :consume_garments 
  end
  
  get 'consume_garments/cal_cost', to: 'consume_garments#cal_cost'

  
  resources :types

  resources :clients do
      get :autocomplete_city_name, :on => :collection
  end  

  resources :docs

  resources :cities

  resources :regions

  resources :countries

  get "activate" => 'activations#create'

  root :to => "pages#home"

  
  get  "inventory" => "pages#inventory", :as => "inventory"
  get  "admin" => "pages#admin", :as => "admin"

  get "about" => "pages#about", :as => "about"

  resources :users do
      member do
        get :activate
      end
      get :autocomplete_center_name, :on => :collection
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :sessions, :only => [:new, :create, :destroy]

  resource :password_resets, :controller => "password_resets" #, :only => [:new, :edit]
  
  resources :centers
  resources :regionals
  resources :occupations

  resources :productions do
    collection do
         get :bars
    end
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

   def index
     @categories = Category.page(params[:page]).per_page(3).order('id DESC')
     respond_to do |format|
       format.html # index.html.erb
       format.json { render json: @categories } 
     end
   end

    def show
        @category = Category.find(params[:id])
    end

    def new
        @category = Category.new
    end

    def edit
        @category = Category.find(params[:id])
    end

    def create
        @category = Category.new(params[:category])
        render :action => :new unless @category.save
    end

    def update
        @category = Category.find(params[:id])
        render :action => :edit unless @category.update_attributes(params[:category])
    end

    def destroy
        @category = Category.find(params[:id])
        @category.destroy
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
 <tr id=<%= "category_#{category.id}" %>>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td>
      <%= link_to image_tag('edit.png', :width=>'30', :title=>'Editar' ), edit_category_path(category), :remote => true %> |
      <%= link_to image_tag('destroy.png', :width=>'30', :title=>'Eliminar' ), category_path(category),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
    </td>
</tr>

app/views/categories/_form.html.erb
<%= simple_form_for @category, :html => { :remote => true, :class => 'form-horizontal' } do |f| %>

  <div class="responsive">

      <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="$.lazybox.close()">&times;</button>
           <h3>Categorias de Insumos</h3>
      </div>

      <div class="modal-body">
          <%= f.error_notification %>
          <%= display_base_errors @category %>
      	  <div class="control-group">
              <label class="control-label" for="inputName">Nombre</label>
              <div class="controls">
                   <%= f.input :name, :label => false, :required => true,
                       :input_html => {:class => 'span3' } %>
              </div>
          </div>
      	  <div class="control-group">
              <label class="control-label" for="inputName">Descripción</label>
              <div class="controls">
                   <%= f.input :description, :label => false, :required => true,
                       :input_html => {:class => 'span3' } %>
              </div>
          </div>
      </div>

      <div id='fo' class="modal-footer">
           <a href="#" class="btn btn-inverse" onclick="$.lazybox.close()">Cerrar</a>
           <%= f.button :submit, "Guardar", :class => 'btn-primary' %>
      </div>

  </div>

<% end %>

app/views/categories/_show.html.erb
<%- model_class = Category -%>

<div class="responsive">

    <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="$.lazybox.close()">&times;</button>
         <h3>Categorias de Insumos</h3>
    </div>

    <div class="modal-body">

        <dl class="dl-horizontal">
            <dt><strong>Nombre:</strong></dt>
            <dd><%= @category.name %></dd>
            <dt><strong>Descripción:</strong></dt>
            <dd><%= @category.description %></dd>
        </dl>

    </div>

</div>

app/views/categories/create.js.erb
$('table tbody').append("<%= escape_javascript(render @category) %>")
$.lazybox.close()

app/views/categories/destroy.js.erb
$("table tr#category<%= @category.id %>").remove();

app/views/categories/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true, close: false});

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
 <h3 id='order'>Categorias de Insumos</h3>
</div>
<br>
<div id="buscarr">
    <%= form_tag request.path, :class => "well", :method => 'get' do %> 

      <div class = "row">
           <div class="span9">
                <div class = "row">
                     <div class="span5">
                          <b>Ca Insumo</b>
                          <%= text_field_tag :name, params[:name], 
                           :class=>"span4" %>
                     </div>
                     <div class="span1">
                         <%= submit_tag "Buscar", :name => nil, :class => 'btn btn-primary' %>
                     </div>
                      <%= hidden_field_tag :ind, "1" %>
                </div>
           </div>
      </div>

    <% end %>
</div>
<table class="table table-striped">
 <thead>
   <tr>
     <th>Nombre</th>
     <th>Descripción</th>
     <th></th>
   </tr>
 </thead>
 <tbody>
    <%= render @categories %>
 </tbody>
</table>

<%= link_to "Nuevo", new_category_path, :remote => true, 
   :class => 'btn btn-primary' %> 

  <div id='ocupa' class="pagination">
   <%= will_paginate(@categories, :renderer => WillPaginate::ActionView::LinkRenderer,
                                :previous_label => '&laquo; Anterior', 
                                :next_label => 'Siguiente &raquo;') %>
                                
   <p id='total' class="pull-right">Total Categorias : <%= @categories.count %></p>
</div>

app/views/categories/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>", {close: false});

app/views/categories/show.js.erb
$.lazybox("<%= j(render 'show') %>", {close: false, klass: 'sticker', fixed: true})

app/views/categories/update.js.erb
$('tr#category_<%= @category.id %>').replaceWith("<%= escape_javascript(render @category) %>")
$.lazybox.close()