config/routes.rb
Control::Application.routes.draw do

  resources :roles

  resources :entrances


  resources :purchases do
    resources :purchase_descriptions
  end


  resources :suppliers


  get "ingresolo" => "sessions#ingresolo", :as => "ingresolo"
  get "help" => "pages#help", :as => "help"
  get "video1" => "ayuda#video1", :as => "video1"

  resources :receipt_headers do
    get :autocomplete_city_name, :on => :collection
    resources :receipt_descriptions
  end 
  
  get 'receipt_descriptions/calc', to: 'receipt_descriptions#calc' 

  

  resources :conditions


  resources :states


  resources :production_orders do
    resources :procedures do 
  end

    resources :preproduction_costs
  end

  get "statistics" => "statistics#index", :as => "statistics"
  
  resources :statistics do
    collection do
      get :prints
    end
    collection do
      get :assemblies
    end
    collection do
      get :outlines
    end
    collection do
      get :embroideries
    end
    collection do
      get :cuts
    end
    collection do
      get :labels
    end
  end


  resources :donations


  resources :inputs
  resources :categories
  resources :unities
  
  resources :garments do
     resources :consume_garments 
  end
  
  get 'consume_garments/cal_cost', to: 'consume_garments#cal_cost'

  
  resources :types

  resources :clients do
      get :autocomplete_city_name, :on => :collection
  end  

  resources :docs

  resources :cities

  resources :regions

  resources :countries

  get "activate" => 'activations#create'

  root :to => "pages#home"

  
  get  "inventory" => "pages#inventory", :as => "inventory"
  get  "admin" => "pages#admin", :as => "admin"

  get "about" => "pages#about", :as => "about"

  resources :users do
      member do
        get :activate
      end
      get :autocomplete_center_name, :on => :collection
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :sessions, :only => [:new, :create, :destroy]

  resource :password_resets, :controller => "password_resets" #, :only => [:new, :edit]
  
  resources :centers
  resources :regionals
  resources :occupations

  resources :productions do
    collection do
         get :bars
    end
  end
  
end

app/models/entrance.rb
class Entrance < ActiveRecord::Base
  
  belongs_to :input	
  attr_accessible :amount, :input_id, :date
end

app/controllers/entrances_controller.rb
class EntrancesController < ApplicationController

  before_filter :find_id

  def index
   @entrances = Entrance.page(params[:page]).per_page(3).order('id DESC')
     respond_to do |format|
     format.html # index.html.erb
     format.json { render json: @entrances }
   end 
  end

  def show

  end

  def new
    @entrance = Entrance.new

  end

  def edit

  end

  def create
    @entrance =  Entrance.new(params[:entrance])
    @input = Input.find(@entrance.input_id)
    @input.stock += @entrance.amount
    @input.save
    render :action => :new unless @entrance.save
  end

  def update
    @input = Input.find(@entrance.input_id)
    @input.stock -= @entrance.amount

    if @entrance.update_attributes(params[:entrance])
      @input.stock += @entrance.amount
      @input.save
      @entrance.save
     else
      render :action => :edit
    end
  end

  def destroy
    @input = Input.find(@entrance.input_id)
    @input.stock -= @entrance.amount
    @input.save
    @entrance.destroy
  end

  def find_id
    @entrance= Entrance.find(params[:id]) if params[:id]
  end
  
end

app/helpers/entrances_helper.rb
module EntrancesHelper
end

app/views/entrances/_entrance.html.erb
<tr id=<%= "entrance_#{entrance.id}" %>>
 <td><%= entrance.input.name %></td>
 <td><%= entrance.amount %></td>
 <td>
   <%= link_to image_tag('ver.png', :width=>'30', :title=>'Mostrar' ), entrance, :remote => true %> |
   <%= link_to image_tag('edit.png', :width=>'30', :title=>'Editar' ), edit_entrance_path(entrance), :remote => true %> |
   <%= link_to image_tag('destroy.png', :width=>'30', :title=>'Eliminar' ), entrance_path(entrance), 
       :data => { :confirm => 'Esta Seguro?' },
       :method => :delete, :remote => true %>
 </td>
</tr>

app/views/entrances/_form.html.erb
<br>
<%= javascript_include_tag "entrances.js" %>
<h3 id='order'>Nueva Entrada</h3>
<%= simple_form_for @entrance, :html => { :remote => true, :class => 'form-horizontal' } do |f| %>

  <div class="responsive">
      
     <div class="modal-body">  
         
        <%= f.error_notification %>
        <%= display_base_errors @entrance %>
        
        <div class="row">
            <div class="span6">

                <div class="control-group">
                    <label class="control-label" for="inputName">Prenda</label>
                    <div class="controls">
                        <%= f.association :input, :collection => Input.all(:order => 'name'),
                             :label => false, :required => true,
                             :input_html => {:class => 'span4' } %>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputName">Cantidad</label>
                    <div class="controls">
                         <%= f.input :amount,:label => false, :required => true,
                             :input_html => {:class => 'span4' } %>
                    </div>
                </div>
                <div class="control-group">
                  <label class="control-label" for="inputName">Fecha</label>
                  <div class="controls">
                      <%= f.input :date, :label => false, :required => true, :input_html => { :class => 'span4 datepicker' } %>
                   </div>
                </div>
            </div>
        </div> 
     
        <div id='fo' class="modal-footer">
            <a href="#" class="btn btn-inverse" onclick="$.lazybox.close()">Cerrar</a>
            <%= f.button :submit, "Guardar", :class => 'btn-primary' %>
        </div>
  
  </div>
<% end %>

app/views/entrances/_show.html.erb
<div class="entrance">
  <dt><strong>Prenda</strong></dt>
  <dd><%= @entrance.input.name %></dd>
  <dt><strong>Cantidad</strong></dt>
  <dd><%= @entrance.amount %></dd>

</div>
 

 

app/views/entrances/create.js.erb
$('table tbody').append("<%= escape_javascript(render @entrance) %>")
$.lazybox.close()

app/views/entrances/destroy.js.erb
$("table tr#entrance_<%= @entrance.id %>").remove();

app/views/entrances/index.html.erb
<%- model_class = Entrance -%>
<div class="page-header">
 <h3 id='order'>Entradas</h3>
</div>
<br>
 <table class="table table-striped">
 <thead>
   <tr>
     <th>Prenda</th>
		 <th>Cantidad</th>
     <th></th>
   </tr>
 </thead>
 <tbody>
     <%=render @entrances%>
 </tbody>
 <tfoot>
 </tfoot>
</table>

<br> 

<%= link_to 'Nueva Entrada', new_entrance_path, :remote => true, :class => 'btn btn-primary' %>

  <div id='ocupa' class="pagination">
   <%= will_paginate(@entrances, :renderer => WillPaginate::ActionView::LinkRenderer,
                                :previous_label => '&laquo; Anterior', 
                                :next_label => 'Siguiente &raquo;') %>

   <br>                             
                                
   <p id='total' class="pull-right"> Total entradas : <%= @entrances.count %> </p>
</div>

app/views/entrances/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/entrances/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/entrances/update.js.erb
$('tr#entrance_<%= @entrance.id %>').replaceWith("<%= escape_javascript(render @entrance) %>")
$.lazybox.close()